### ISSUE TITLE
How to deal with missing data (NA) of SNPs in GF

### ISSUE THREAD

**Issue by chenyiyong123abc** [pgugger/LandscapeGenomics#1]
Hi, gugger,
When I used the lastest version of gradientForest package in R, it reported an Error with "**NA not permiteed in response**".  But it is OK when I used one old version. 

_**How should I deal with NA values in snp.012 data ?**_

The lastest version of gradientForest was installed R by using {install.packages("gradientForest", repos="http://R-Forge.R-project.org")}. The version of GF is 0.1.32. 

Great thanks,
Yiyong

**Comment by pgugger** [comment]
Hi, if you need complete SNP data you could filter for complete data if you think the data are missing at random (perhaps unlikely), or you could use one of various imputation methods. The simplest imputation method is to use column averages in place of missing values. One better would be to consider population structure such as the one in the LEA R package. Or if your species is a model system you can use more sophisticated methods.  

Hope this helps.
