### ISSUE TITLE
About the input file sample.coord.txt

### ISSUE THREAD

**Issue by HengLiang1993** [pgugger/LandscapeGenomics#2]
Hi
base on the code, 'sample.coord <-read.table("sample.coord.txt", header=T, stringsAsFactors=F)', I can not find the input in the project.

could you provide the input file sample.coord.txt or path to me?

Best

Heng

**Comment by pgugger** [comment]
Hi, Here are the input files:
https://drive.google.com/drive/folders/1HJH6OQF6D18Bz_YV1WBTq-LaTKyWu4Kl?usp=sharing

Paul
